package pdf

import (
	"bytes"
	"fmt"
	"strings"
	"time"

	"go-service/student"

	"github.com/jung-kurt/gofpdf"
)

// Generator handles PDF report generation
type Generator struct{}

// NewGenerator creates a new PDF generator
func NewGenerator() *Generator {
	return &Generator{}
}

// GenerateStudentReport creates a PDF report for the given student
func (p *Generator) GenerateStudentReport(student *student.Student) ([]byte, error) {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.AddPage()

	// Set margins
	pdf.SetMargins(20, 20, 20)

	// Title
	pdf.SetFont("Arial", "B", 20)
	pdf.SetTextColor(0, 100, 200)
	pdf.CellFormat(0, 15, "STUDENT REPORT", "0", 1, "C", false, 0, "")
	pdf.Ln(10)

	// Student Photo Placeholder
	pdf.SetFillColor(240, 240, 240)
	pdf.Rect(20, pdf.GetY(), 40, 50, "F")
	pdf.SetFont("Arial", "I", 10)
	pdf.SetTextColor(100, 100, 100)
	pdf.SetXY(25, pdf.GetY()+20)
	pdf.Cell(30, 10, "Photo")
	pdf.SetXY(20, pdf.GetY()+35)

	// Basic Information Header
	pdf.SetFont("Arial", "B", 16)
	pdf.SetTextColor(0, 0, 0)
	pdf.SetXY(70, 45)
	pdf.Cell(0, 10, "BASIC INFORMATION")
	pdf.Ln(5)

	// Basic Information
	pdf.SetFont("Arial", "", 12)
	yPos := 55
	basicInfo := [][]string{
		{"Name:", student.Name},
		{"Student ID:", fmt.Sprintf("%d", student.ID)},
		{"Email:", student.Email},
		{"Phone:", student.Phone},
		{"Gender:", student.Gender},
		{"Date of Birth:", p.formatDate(student.DOB)},
	}

	for _, info := range basicInfo {
		pdf.SetXY(70, float64(yPos))
		pdf.SetFont("Arial", "B", 12)
		pdf.Cell(40, 7, info[0])
		pdf.SetFont("Arial", "", 12)
		pdf.Cell(0, 7, info[1])
		yPos += 8
	}

	// Academic Information
	pdf.SetY(float64(yPos + 10))
	pdf.SetFont("Arial", "B", 16)
	pdf.SetTextColor(0, 100, 200)
	pdf.Cell(0, 10, "ACADEMIC INFORMATION")
	pdf.Ln(8)

	academicInfo := [][]string{
		{"Class:", student.Class},
		{"Section:", student.Section},
		{"Roll Number:", fmt.Sprintf("%d", student.Roll)},
		{"Admission Date:", p.formatDate(student.AdmissionDate)},
		{"System Access:", p.boolToYesNo(student.SystemAccess)},
	}

	pdf.SetFont("Arial", "", 12)
	pdf.SetTextColor(0, 0, 0)
	for _, info := range academicInfo {
		pdf.SetFont("Arial", "B", 12)
		pdf.Cell(50, 7, info[0])
		pdf.SetFont("Arial", "", 12)
		pdf.Cell(0, 7, info[1])
		pdf.Ln(8)
	}

	// Family Information
	pdf.Ln(5)
	pdf.SetFont("Arial", "B", 16)
	pdf.SetTextColor(0, 100, 200)
	pdf.Cell(0, 10, "FAMILY INFORMATION")
	pdf.Ln(8)

	familyInfo := [][]string{
		{"Father's Name:", student.FatherName},
		{"Father's Phone:", student.FatherPhone},
		{"Mother's Name:", student.MotherName},
		{"Mother's Phone:", student.MotherPhone},
		{"Guardian Name:", student.GuardianName},
		{"Guardian Phone:", student.GuardianPhone},
		{"Relation of Guardian:", student.RelationOfGuardian},
	}

	pdf.SetFont("Arial", "", 12)
	pdf.SetTextColor(0, 0, 0)
	for _, info := range familyInfo {
		pdf.SetFont("Arial", "B", 12)
		pdf.Cell(50, 7, info[0])
		pdf.SetFont("Arial", "", 12)
		pdf.Cell(0, 7, info[1])
		pdf.Ln(8)
	}

	// Address Information
	pdf.Ln(5)
	pdf.SetFont("Arial", "B", 16)
	pdf.SetTextColor(0, 100, 200)
	pdf.Cell(0, 10, "ADDRESS INFORMATION")
	pdf.Ln(8)

	// Current Address
	pdf.SetFont("Arial", "B", 12)
	pdf.SetTextColor(0, 0, 0)
	pdf.Cell(0, 7, "Current Address:")
	pdf.Ln(8)
	pdf.SetFont("Arial", "", 11)
	pdf.MultiCell(0, 6, p.wrapText(student.CurrentAddress, 80), "0", "L", false)
	pdf.Ln(3)

	// Permanent Address
	pdf.SetFont("Arial", "B", 12)
	pdf.Cell(0, 7, "Permanent Address:")
	pdf.Ln(8)
	pdf.SetFont("Arial", "", 11)
	pdf.MultiCell(0, 6, p.wrapText(student.PermanentAddress, 80), "0", "L", false)

	// Footer
	pdf.SetY(-30)
	pdf.SetFont("Arial", "I", 10)
	pdf.SetTextColor(100, 100, 100)
	pdf.Cell(0, 10, fmt.Sprintf("Report generated by: %s", student.ReporterName))
	pdf.Ln(5)
	pdf.Cell(0, 10, fmt.Sprintf("Generated on: %s", time.Now().Format("January 2, 2006 at 3:04 PM")))

	// Get PDF bytes
	var buf bytes.Buffer
	err := pdf.Output(&buf)
	if err != nil {
		return nil, err
	}
	
	return buf.Bytes(), nil
}

// formatDate formats the date string to a more readable format
func (p *Generator) formatDate(dateStr string) string {
	if dateStr == "" {
		return "N/A"
	}
	
	t, err := time.Parse("2006-01-02T15:04:05.000Z", dateStr)
	if err != nil {
		return dateStr
	}
	
	return t.Format("January 2, 2006")
}

// boolToYesNo converts boolean to Yes/No string
func (p *Generator) boolToYesNo(b bool) string {
	if b {
		return "Yes"
	}
	return "No"
}

// wrapText wraps text to specified width (approximate)
func (p *Generator) wrapText(text string, width int) string {
	if len(text) <= width {
		return text
	}
	
	words := strings.Fields(text)
	var lines []string
	var currentLine string
	
	for _, word := range words {
		if len(currentLine)+len(word)+1 <= width {
			if currentLine == "" {
				currentLine = word
			} else {
				currentLine += " " + word
			}
		} else {
			if currentLine != "" {
				lines = append(lines, currentLine)
			}
			currentLine = word
		}
	}
	
	if currentLine != "" {
		lines = append(lines, currentLine)
	}
	
	return strings.Join(lines, "\n")
}